### ISSUE TITLE
tried to generate test and received error "Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by wdunn001** [allenhwkim/ngentest#19]
(node:12436) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at forEach.param (C:\Users\Jason\AppData\Roaming\npm\node_modules\ngentest\src\get-directive-data.js:86:26)
    at Array.forEach (<anonymous>)
    at getDirectiveData (C:\Users\Jason\AppData\Roaming\npm\node_modules\ngentest\src\get-directive-data.js:53:43)
    at parseTypescript.then.tsParsed (C:\Users\Jason\AppData\Roaming\npm\node_modules\ngentest\index.js:44:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:12436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ability-app** [comment]
can you release the fix via npm, have the same issue ?

**Comment by ability-app** [comment]
In my case the error was caused by:

```
    constructor(
        @Inject(APP_CONFIG) public config: IAppConfig,
        protected ref: ChangeDetectorRef,
        protected notificationService: NotificationService,
        protected selectableService: SelectableService,
        **protected searchObject: BehaviorSubject<SearchModel>,**
        protected eventService: EventService,
        **protected el?: ElementRef,
        protected collectionLayout?: BehaviorSubject<LayoutTypeEnum>**
    ) {

```

special characters inside the constructor

**Comment by ability-app** [comment]
**<SearchModel>** and the **?** before the variable
