### ISSUE TITLE
Hi i am getting following typeError while running the command ngentest.

### ISSUE THREAD

**Issue by subrat7** [allenhwkim/ngentest#26]
const tsFile = argv._[0].replace(/\.spec\.ts$/, '.ts');
                         ^

TypeError: Cannot read property 'replace' of undefined                                                                      at Object.<anonymous> (C:\Users\20122701\AppData\Roaming\npm\node_modules\ngentest\index.js:43:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                                         at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)                                                                          at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Please help me,
Thanks in advance.

**Comment by allenhwkim** [comment]
This has been tested with Mac.
Please provide your full command outputs. I may need to do some for windows.

**Comment by subrat7** [comment]
thanks 
It worked for me :)
