### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by andsan** [allenhwkim/ngentest#27]
Error: Cannot find module '@sct-ng2/compatibility/services/config.service'
code: 'MODULE_NOT_FOUND',
requireStack: [ '', '/usr/local/lib/node_modules/ngentest/index.js' ]

I guess this tool can't handle paths or moduleNameMapper in the same manner as tsconfig and jest config provides.

 "@sct-ng2/*": ["src/app/*"]

**Comment by Polgabarro** [comment]
This happen also in my project

**Comment by allenhwkim** [comment]
sorry for the late response.  This can be done with replacements. 
From README.md

![image](https://user-images.githubusercontent.com/1437734/75948521-aa516d80-5e71-11ea-82aa-8d0396dc34c1.png)

**Comment by netalex** [comment]
similar error, with custom library
`
{ Error: Cannot find module 'myLibraryName'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)   
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<anonymous>:10:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at requireFromString (C:\Nodist\bin\node_modules\ngentest\node_modules\require-from-string\index.js:28:4)
    at run (C:\Nodist\bin\node_modules\ngentest\index.js:151:21)
    at Object.<anonymous> (C:\Nodist\bin\node_modules\ngentest\index.js:220:3)    
    at Module._compile (internal/modules/cjs/loader.js:778:30) code: 'MODULE_NOT_FOUND' }
`
Can you please suggest how to use replacement on what, to fix it? Tank you

**Comment by allenhwkim** [comment]
Can someone build a simple project to replicate this issue? I can do it but too busy with bill-paying tasks.

**Comment by allenhwkim** [comment]
closing because of inactivity
