### ISSUE TITLE
Reference Error: document is undefined 

### ISSUE THREAD

**Issue by mdjack78** [allenhwkim/ngentest#29]
When I run this command from the directory that contains my .ts file: 
$ ngentest link-options.service.ts -s

I get this output:
ReferenceError: document is not defined

at Object.<anonymous> (C:\gitRepos\mdl_common\node_modules\custom-event\index.js:24:23)

at Module._compile (internal/modules/cjs/loader.js:689:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

at Module.load (internal/modules/cjs/loader.js:599:32)

at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

at Function.Module._load (internal/modules/cjs/loader.js:530:3)

at Module.require (internal/modules/cjs/loader.js:637:17)

at require (internal/modules/cjs/helpers.js:22:18)

at Object.<anonymous> (C:\gitRepos\mdl_common\node_modules\crossvent\src\crossvent.js:3:19)

at Module._compile (internal/modules/cjs/loader.js:689:30)

 

I am using the Full Example ngentest.config.js

**Comment by mdjack78** [comment]
I'm on Windows 10.

**Comment by allenhwkim** [comment]
sorry for the late resp. can you provide your `link-options.service.ts`?

**Comment by allenhwkim** [comment]
no detail, closing
