### ISSUE TITLE
Error generating for close method

### ISSUE THREAD

**Issue by caugustr** [allenhwkim/ngentest#47]
When i have a component with this method, i receved this error, have some replace i can do to resolve?
```
 private closeLoadJava() {
        if (typeof (<any>window).closeLoad === "function") {
            (<any>window).closeLoad();
        }
    }
```
    
    

>     TypeError: target[firstKey] is not a function
>     at Function.merge (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\util.js:150:88)
>     at Function.merge (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\util.js:176:12)
>     at FuncTestGen.setPropsOrParams (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:279:14)
>     at FuncTestGen.setMockData (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:161:12)
>     at FuncTestGen.setMockData (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:90:12)
>     at C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:80:14
>     at Array.forEach (<anonymous>)
>     at FuncTestGen.setMockData (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:79:17)
>     at FuncTestGen.setMockData (C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\src\func-test-gen.js:104:12)
>     at C:\Users\caugustr\AppData\Roaming\npm\node_modules\ngentest\index.js:78:17

**Comment by allenhwkim** [comment]
I need to look at this carefully, It seems `window` is problematic. Will get back to you

**Comment by allenhwkim** [comment]
This was a bug. Fixed and released, ngentest 1.4.4 is released
