### ISSUE TITLE
className is not defined

### ISSUE THREAD

**Issue by Anandcs2** [allenhwkim/ngentest#7]
While trying to run ngentest getting the below error,

```
ReferenceError: ejs:18
    16| <% } -%>
    17|
 >> 18| describe('<%= className %>', () => {
    19|   let fixture;
    20|   let component;
    21|

className is not defined
    at eval (eval at compile (/Users/XXXX/.nvm/versions/node/v9.4.0/lib/node_modules/ngentest/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:30:26)
    at returnedFn (/Users/XXXX/.nvm/versions/node/v9.4.0/lib/node_modules/ngentest/node_modules/ejs/lib/ejs.js:653:17)
    at Object.exports.render (/Users/XXXX/.nvm/versions/node/v9.4.0/lib/node_modules/ngentest/node_modules/ejs/lib/ejs.js:416:37)
    at parseTypescript.then.tsParsed (/Users/XXXX/.nvm/versions/node/v9.4.0/lib/node_modules/ngentest/index.js:46:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
```

**Comment by allenhwkim** [comment]
Please provide .ts file sample for this
